//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.02 at 12:18:00 PM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hackathon.hcl.com/Transfer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hcl.hackathon.transfer;
